# Assignment 2
Q1: Derive the negative log-likelihood cost function J(x, y; θ)
Consider the following regression network:
\begin{equation*}
    f(x;w,b) = w^Tx+b
\end{equation*}
And the model has a Gaussian distribution of prediction errors and with a unity covariance matrix $p(y_i;\theta)$, whereas the mean is $f(x_i;\theta)$ and variance is one.\newline
It is known that the negative log-likelihood cost function is:
\begin{equation*}
    J(\theta) = -log\Pi^{m-1}_{i=0}\hat{P}_{model}(y^{(i)}|x^{(i)},\theta)
\end{equation*}
The ML estimate is the minimizer of the negative log likelihood function with $J(x,y|\theta)$. Where it is known that the negative likelihood cost function is:
\begin{equation*}
    J(\theta) = arg\min_{\theta}(-\sum log \hat{p}_{model}(y^{(i)}|x^{(i)},\theta))
\end{equation*}
As well as given Gaussian distribution model parameters with mean and variance. The model of probability model of $\hat{p}_{model}~\mathcal{N}\{y;f(x,\theta),\sigma I\}$ since the output, $p(y_i;\theta)$ follows normally distribution. Here, the mean is $f(x_i;\theta)$.
Hence, it follows that the estimator of w and b satisfy following:
\begin{equation*}
    (\hat{\theta}) = arg\min_{\theta}(-\frac{1}{m}\sum^{m-1}_{i=0}log \hat{P}_{model(y^i|x^i,\theta)}) =  arg\min_{\theta}(-\frac{1}{m}\sum^{m-1}_{i=0}log\: e^{-\frac{1}{2\sigma^2}[y^i-f(x^i;\theta)][y^i-f(x^i;\theta)]^T})
\end{equation*}
Where the $\theta $ equals to $(w,b)$.
Furthermore, it can develop the probability model which is satisfied as Gaussian normal distribution with the given variance as 1, so the equation can be derived into:
\begin{equation*}
    m\:ln\sqrt{2\pi}+\sum^{m-1}_{i=0}\frac{((y_i-f(x_i;\theta))^2}{2}
\end{equation*}

# Q2 
Get expression for w and b.
The expression for the w and b from above can be derived by minimum MSE cost criterion.
\begin{equation*}
    \frac{\partial J}{\partial w}=\sum_{0}^{m-1}\left\{\left[y_{i}-\left(w^{\top} x_{i}+b\right)\right] \cdot(- x_{i})\right\}=0
\end{equation*}
\begin{equation*}
    \frac{\partial J}{\partial b}=\sum_{0}^{m-1}\left\{\left[y_{i}-\left(w^{\top} x_{i}+b\right)\right] \cdot (-1)\right)=0
\end{equation*}
From the equations above, the weight w and b thus can be derived as following:
\begin{equation*}
    \sum y_{i}=\sum w^T x_{i}+m b
\end{equation*}
\begin{equation*}
    b= \sum\left(y_{i}-w^{\top} x_{i}\right)
\end{equation*}
With cost function:
\begin{equation*}
    \frac{\partial J(\theta)}{\partial \theta}= \sum \{ [y_i - f(x;\theta)]\cdot f(x;\theta)\}=0
\end{equation*}\\
Where actucally, the $ (y-f(x_i;\theta))^2 = (y-\theta^Tx)\cdot (y-\theta^Tx)^T$, hence the $\theta$ here is the $\theta = (XX^T)^{-1}Xy^T$.


# Q3 and Q4
## Q3
Calculate the b and w. 
So in the Q3, the given point is well described.

## Q4
And result showing that the given parameters are not be capable of reverting back to the model.

In [25]:
import numpy as np
import pandas as pd



def is_invertible(a):
    return a.shape[0] == a.shape[1] and np.linalg.matrix_rank(a) == a.shape[0]

X = np.array([[1,0,0],[1,0.1,1],[1,1,0.2],[1,1,1]]).T
Y = np.array([0, 0.41, 0.18, 0.5]).reshape(1,4)
print(X)
print(np.shape(Y.T))
t = np.linalg.inv(X@X.T)@X@Y.T # w
print('the resulst of b, w :',t.T)

print(is_invertible(t))
print()

Q4= np.array([-0.0416,0.3610,0.1222,0.4733]).reshape(1,4)
q4 = np.linalg.inv(X@X.T)@X@Q4.T 
print(q4)
print(is_invertible(q4))




[[1.  1.  1.  1. ]
 [0.  0.1 1.  1. ]
 [0.  1.  0.2 1. ]]
(4, 1)
the resulst of b, w : [[-1.87350135e-16  1.00000000e-01  4.00000000e-01]]
False
[[-0.05022928]
 [ 0.10107389]
 [ 0.41070998]]
False


# Q5
Derive the optimal ngative log-likelihood cost criterion for a diagonal covariance matrix with $\sigma_0,... \sigma_N...$ on the diagnoal. 

\begin{aligned}
J(\theta) &=-\sum_{i=0}^{m-1}\left[\ln \frac{1}{\sqrt{2 \pi} \cdot \sigma} e^{-\frac{(y-\mu)^{2}}{2 \sigma}}\right]=m \ln \sqrt{2 \pi} \cdot \sigma+\sum_{i=0}^{m-1} \frac{(y-\mu)^{2}}{2 \sigma^{2}} \\
&\left.=m \ln \sqrt{2 \pi}+\sum_{i=0}^{m-1} \frac{1}{2}\left(\frac{\left[y_{1}-f\left(x_{i} ; \theta)\right]^{2}\right.}{\sigma}\right)\right
\end{aligned}
Where the covariance can be derived as following:
\begin{equation*}
    \left[\begin{array}{llll}
\sigma_{1} & & \\
& \sigma_{2} & \\
& & \sigma_{3} & \\
& & \sigma_{N}
\end{array}\right] \Rightarrow\left[\begin{array}{lllll}
\sigma_{1} & \sigma_{2} & \sigma_{3} & \cdots & \sigma_{N}
\end{array}\right] \cdot\left[\begin{array}{c}
I
\end{array}\right]
\end{equation*}

# Q6
## Learning a new funciton, the XOR.
### Optimal parameters with XOR of rule.
Based on the four possible inputs and outputs of the XOR function.
Assume that given input of x data is

In [54]:
X = np.array([[1,0,0],[1,1,1],[1,1,0],[1,0,1]]).T
x = np.array([[0,0],[1,1],[1,0],[0,1]])
print(X)
Y = np.array([0, 0.41, 0.18, 0.5]).reshape(1,4)
q6= np.linalg.inv(X@X.T)@X@Y.T # w
print(q6)

w_1 = np.array([q6[1],q6[2]])
print(w_1.T)
print(x)
print(w_1.T@x.T+q6[0])

[[1 1 1 1]
 [0 1 1 0]
 [0 1 0 1]]
[[0.0675]
 [0.045 ]
 [0.365 ]]
[[0.045 0.365]]
[[0 0]
 [1 1]
 [1 0]
 [0 1]]
[[0.0675 0.4775 0.1125 0.4325]]


# Q8
when $x>> 0$.\
## ReLU
From the gradient of the ReLU, the value is either to 1 when x is over 0 or to 0 when x is less than 0.
##  

# Q9
In this turn, it allows you to model a response variable that varies non-linearly with its explanatory variables. In order to map the correlation from the given iniput, however, singals that are transer from linear layer to another linear layer will just give you linear function.

# Q10


In [14]:
import numpy as np
import pandas as pd
# Input from slide
# Given
W1 = np.array([[1,1],[1,1]])
b = np.array([[0],[-1]])
b2 = 0
W2 = np.array([[1],[-2]])
X = np.array([[0,0,1,1],[0,1,0,1]])
Y = np.array([0,1,1,0]).reshape(1,4)
print(Y)

[[0 1 1 0]]
